import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useEffect } from "react";
import styled from "styled-components";
import { useRouter } from 'next/router'

import { projects_data } from '../../public/data.js';

export default function Projects() {

    const [data, setData] = useState([])

    const router = useRouter()
    // console.log(data.screenshots, "data")

    useEffect(() => {
        if (router.query.id) {
            setData(projects_data[router.query.id])
        }
    });

    return (
        <>
            <Head>
                <title>Josh Renema | Projects</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="./icons/logo.png" />
            </Head>

            <br />
            <div>{data.id}</div>
            <div>{data.title}</div>
            <div>{data.desc}</div>
            <Image height="50px" width="50px" objectFit="contain" src={data.icon} />
            <div>{data.github_link}</div>
            <div>{data.link}</div>
            {/* {data.screenshots.map((o, index) => {
                return (
                    <Image key={index} height="500px" width="200px" objectFit="contain" src={o.src} />
                )
            })} */}
            <br />
        </>
    )
}
