import React, { } from "react";
import Head from 'next/head'
import '../styles/globals.css'
import useColorTheme from "use-color-theme";
import SideBar from "../comps/SideBar";
import { projects_data } from '../public/data.js';

if (typeof window !== 'undefined' && localStorage.colorTheme !== '"dark-theme"') {
  localStorage.setItem("colorTheme", '"light-theme"');
} else if (typeof window !== 'undefined' && localStorage.colorTheme !== '"light-theme"') {
  localStorage.setItem("colorTheme", '"dark-theme"');
}

function MyApp({ Component, pageProps }) {

  const colorTheme = useColorTheme("light-theme", {
    classNames: ["light-theme", "dark-theme"],
  });

  let sun_moon = "";
  let github = "";
  let linkedin = "";
  let email = "";
  let behance = "";
  let logo = "";
  if (colorTheme.value === "light-theme") {
    sun_moon = "/icons/sun.svg";
    github = "/icons/github.svg";
    linkedin = "/icons/linkedin.svg";
    email = "/icons/email.svg";
    behance = "/icons/behance.svg";
    logo = "/icons/logo.svg";
  } else if (colorTheme.value === "dark-theme") {
    sun_moon = "/icons/moon_w.svg";
    github = "/icons/github_w.svg";
    linkedin = "/icons/linkedin_w.svg";
    email = "/icons/email_w.svg";
    behance = "/icons/behance_w.svg";
    logo = "/icons/logo_w.svg";
  }


  return (
    <div>
      <Head>
        <title>Josh Renema</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./icons/logo.png" />
      </Head>
      {/* BODY */}
      <div style={{ display: "flex", flexDirection: "row" }}>
        {/* SIDE */}
        <SideBar logo_src={logo} sm_src={sun_moon} onClick={() => { colorTheme.toggle() }} data={projects_data} />
        {/* MAIN */}
        <div style={{
          position: "relative",
          width: "calc(100vw - 333px)",
          left: '333px',
          minHeight: "100vh",
          background: 'var(--secondary)',

          display: 'grid',
          gridTemplateColumns: '1fr 3fr 1fr',
          gridTemplateRows: '1fr',
          gap: '0px 0px',
          gridTemplateAreas: "fill content fill",
        }}>
          <div className="fill"></div>
          {/* CONTENT */}
          <div className="content" style={{margin:"6em 0"}}>
            <Component {...pageProps} />
          </div>
          <div className="fill"></div>
        </div>
      </div>
    </div >
  )
}

export default MyApp
